### PR TITLE
Fix minetweaker for 1.10.2 backport

### LINKED ISSUE #935: [1.10.2] Minetweaker recipes not showing up in JEI
All these versions are most recent available on the curse launcher at the time of this posting
JEI-1.10.2-3.14.3.403
Techreborn-1.10.2-2.1.2.160
RebornCore-1.10.2-2.13.2.114
Crafttweaker -1.10.2-3.0.17
Forge 2221

I've only tried a few different ones, but it seems that any MT machine recipes that I add won't show up in JEI after refreshing, but will still function correctly. I haven't taken a peek at the relevant code yet, but I suspect it's related to crafttweaker API updates (see [here](https://github.com/jaredlll08/CraftTweaker/issues/136) and [here](https://github.com/SonarSonic/Calculator/issues/202) for what seems to be a similar case)

### PR DESCRIPTION
**Pull request by ghost**
Copied directly from 1.10.2-v1, fixes #935

### CODE REVIEW

**Comment by modmuss50** [comment]
Nice thanks, I plan to upload a new 1.10 version tonight with a few other fixes as well.

**Comment by superdave4054** [comment]
I'm not a modder/coder so please be patient with my question. Did the commit 74040c0 fix the issue with JEI not reflecting the new MT script changes? I ask because I'm having the same problem with a pack I'm building. I saw the file path listed at the top of the commit and couldn't figure out where I would go to find that code. 
Thanks, 
Dave

**Comment by modmuss50** [comment]
It looks like I need to test with the newest MT and JEI. I will write up the wiki page while I'm at it.

**Comment by ghost** [comment]
It worked when I tested it outside of dev. I'm currently using it successfully in one of my packs.

**Comment by superdave4054** [comment]
I'm curious where you put the code. I couldn't find anything remotely close
to the file path listed to paste it. Bottom line is the pack would have a
more "finished" feeling if things worked as intended.
Thank you for helping.

**Comment by ghost** [comment]
Do you mean this directory? https://github.com/TechReborn/TechReborn/tree/1.10.2-backport/src/main/java/techreborn/compat/minetweaker

I'm not sure if I exactly understand what you're asking

**Pull request merged**
