### PR TITLE
Fix chainsaws don't work for non-wood materials

### LINKED ISSUE #2637: [1.17.1] Chainsaws don't work well with pumpkin
**Describe the bug**
Breaking a pumpkin takes the same time with bare hands when using chainsaws.
EDIT: as @xanthian says, it works fine on trees.

**Steps to Reproduce**
Break a pumpkin with chainsaws.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric
 - Tech Reborn: `TechReborn-5.0.11-beta.jar`

### PR DESCRIPTION
**Pull request by equal-l2**
Fixes #2637.

---

I'm totally a newbie at modding, so feel free to give me any advice!

### CODE REVIEW

**Review by xanthian — COMMENTED** [review]
Rather than removing the existing material check, would it not have been better to add the pumpkin one to it?

state.getMaterial() == Material.GOURD

This would include Carved and Melon

**Comment by equal-l2** [comment]
Adding materials is fine, but is there a reason to list all suitable materials by ourselves, instead of delegating the decision to the vanilla logic?
People would assume chainsaws should work the same way with vanilla axes.

**Comment by equal-l2** [comment]
I think my solution is more future-proof for when Minecraft add new material that is suitable for axes.

**Comment by xanthian** [comment]
just did a test build with both, they both work fine, you're right though best to let vanilla declare it unless anything needs declaring from another mod.

One thing to note, cant carve pumpkins with it.

**Comment by equal-l2** [comment]
> One thing to note, cant carve pumpkins with it.

Thank you for letting me know, it would deserve another issue.

**Comment by equal-l2** [comment]
Wait, carving pumpkins is a job for shears, isn't it?

**Comment by equal-l2** [comment]
Thank you for rapid reviewing and merging!

**Comment by drcrazy** [comment]
This one is merged. Using reference tool is a good idea.

**Comment by xanthian** [comment]
> Wait, carving pumpkins is a job for shears, isn't it?

yes lol.. no idea what i was thinking.. maybe carving with chainsaws isn't such a bad idea 😂

**Comment by equal-l2** [comment]
I remember those days with IC2, when we sheared sheep with a chainsaw :)

**Pull request merged**
