### PR TITLE
add c:wooden_barrels to recipe

### LINKED ISSUE #2838: Crude Storage Unit Recipe
https://github.com/TechReborn/TechReborn/blob/1.18/src/main/resources/data/techreborn/recipes/crafting_table/unit/storage/crude_storage_unit.json
image

Why are we using a mods tag when there are c: tags for barrels and wooden_barrels
c:wooden_barrels seems a better option as this will include betterx and blockus barrels (as well as my own) :D

### PR DESCRIPTION
**Pull request by xanthian**
tested in dev working fine, 
betterx, blockus, eden ring, vanilla and other mods barrels all accepted as viable recipe
fixes #2838

### CODE REVIEW

**Review by Ayutac — CHANGES_REQUESTED** [review]
Just replace the blockus tag with the common tag. blockus barrels are included in that, see https://github.com/Brandcraf06/Blockus/blob/1.18/src/main/java/com/brand/blockus/data/provider/BlockusBlockTagProvider.java

**Comment by xanthian** [comment]
what changes does this need?

**Comment by Ayutac** [comment]
Just remove the blockus:barrels tag, only keep c:wooden_barrels.

Better for maintainability. And blockus has no reason to remove their super tag

**Comment by xanthian** [comment]
> Just remove the blockus:barrels tag, only keep c:wooden_barrels.
> 
> Better for maintainability. And blockus has no reason to remove their super tag

done

**Comment by xanthian** [comment]
actually realised need to make a further addition to this, we need to add c:barrels tag and add vanilla barrel to this, otherwise if someone for whatever reason has no other mods installed it wont work :)

**Comment by Ayutac** [comment]
nice. Can you also remove the blockus tag then I introduced? the whole folder at blockus/tags if you will :)

**Comment by Ayutac** [comment]
whoops, got a bit confused with the review buttons. But it is fine now :)

**Pull request merged**
