### PR TITLE
Proposed fix for #1016

### PR DESCRIPTION
**Pull request by jusvit**
Proposed fix for #1016 

Ignore the  #968 fix, will work on that later.

### CODE REVIEW

**Comment by modmuss50** [comment]
I have a feeling this is an issue with this: https://github.com/Dimmerworld/TechReborn/blob/f94fbb8d08aa08e8e77c8e284392d3b31a5f5457/src/main/java/techreborn/tiles/TileIronFurnace.java#L177

**Comment by jusvit** [comment]
Tried messing with that, to no avail(someone else might have better luck). The current switcharoo seems to work flawlessly(excluding the preexisting quarks with the furnace)

**Comment by modmuss50** [comment]
Humm, ok. I will take a look at the PR another day

**Comment by modmuss50** [comment]
Doing this will also break past tiles. I need to look at the issue in more detail.

**Pull request closed without merging**
