### PR TITLE
Rename Chrome to Chromium

### PR DESCRIPTION
**Pull request by xanthian**
rename chrome > chromium #2621

### CODE REVIEW

**Comment by xanthian** [comment]
unsure if this was wanted/needed.
feel free to reject if not.

**Review by modmuss50 — APPROVED** [review]
Seems fine for me

**Comment by Technici4n** [comment]
Which tag did we use in MI again? Might be `c:chromium_blocks` or so.

**Comment by xanthian** [comment]
> Which tag did we use in MI again? Might be `c:chromium_blocks` or so.

good point, not added/updated tags, dont merge this yet.

**Comment by Ayutac** [comment]
NO! We do NOT change established tag names. I don't care if the displayed name is changed, but leave your fingers off variable names.

We don't need to create ambiguity with tags. This will only lead to different mods using different variants. Keep it clean, stick to lang file only.

**Comment by Technici4n** [comment]
MI is already using `c:chromium_xxx` tags though. Changing the tag in TR will reduce the ambiguity...

**Comment by Ayutac** [comment]
@Technici4n can you check the other main tech mods for their tag? might do it right for all at once, if we do it at all

**Comment by Technici4n** [comment]
I believe only MI and TR have chromium materials.

**Pull request closed without merging**
