### PR TITLE
Added new textures + translation optimizations

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Some of the textures are already made by me :)
If you don't like them / aren't good enough, just contact me and I will try to make better ones...

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
Now it's working ^^

**Comment by Yulife** [comment]
Wait, we have most of those in Unity style o_O

**Comment by ThexXTURBOXx** [comment]
Do you mean the textures? I tried to make them like the other ones... Some of the textures were already in the mod, but their file names had typos (most of the typos were case-errors)

**Comment by Yulife** [comment]
I wouldn't make new textures as the ones of Unity are already there

**Comment by ThexXTURBOXx** [comment]
I only make New textures, wenn there are none Existing ones

**Comment by ThexXTURBOXx** [comment]
I need to remove the old textures first and the rename them and then push the same ones with other names (I just rename the textures, i don't really delete them and make new ones).

Result: I just rename the existing textures and add new ones, when there are no existing ones

**Comment by ThexXTURBOXx** [comment]
Unfortunately, I am not able to create Fluid textures. Someone else needs to create them...

**Comment by modmuss50** [comment]
I was going to do some TR stuff tomorrow, but I didnt release TMT was tomorrow. So it may need to wait.

**Comment by ThexXTURBOXx** [comment]
Ok, so this PR is finished, as I can't help more :/
If you want, you can merge it

**Comment by modmuss50** [comment]
Ok, I will take a look at it now

**Comment by modmuss50** [comment]
Looks good, I think I will move to the new textures soon anyway

**Comment by ThexXTURBOXx** [comment]
Ok, whenever you need some other help, I will be there :)
P.S.: I will start with the German translation for this mod tomorrow

**Pull request merged**
