### PR TITLE
Update to REI 6

### PR DESCRIPTION
**Pull request by shedaniel**
image

I couldn't get into the world (even after disabling REI), so this isn't tested.

Signed-off-by: shedaniel <daniel@shedaniel.me>

### CODE REVIEW

**Comment by modmuss50** [comment]
Seems to be mostly working 👍  Just some rendering issues around the power bar. No idea why you couldnt load the world? What was happening?


Screenshot 2021-06-02 at 20 41 33

Im happy to merge this and fix the remaining issues.

**Comment by shedaniel** [comment]
Yep, still can't get into a world, it is stuck at 100% no matter what I try, it should be pretty easy to fix the remaining issues though :p

**Comment by modmuss50** [comment]
Great, many thanks for this 👍

**Comment by bentterp** [comment]
build 22 works for me together with REI, thank you!

**Pull request merged**
