### PR TITLE
Fixed activation of root advancement.

### PR DESCRIPTION
**Pull request by Ayutac**
Fixed activation of root advancement.

### CODE REVIEW

**Review by Technici4n — CHANGES_REQUESTED** [review]
The tag changes should be done in datagen, not manually.

**Comment by modmuss50** [comment]
The data gen setup needs redoing, for now just continue with the jsons.

**Comment by Ayutac** [comment]
> The tag changes should be done in datagen, not manually.

Then that should be commented instead once the redoing is done. It's important people know when changes in a certain area imply changes needed elsewhere.

**Review by modmuss50 — APPROVED** [review]
I wouldn’t worry about data gen too much now.

**Comment by Technici4n** [comment]
> It's important people know when changes in a certain area imply changes needed elsewhere.

The whole point of moving to datagen is so that the changes only need to be done in one place...

**Comment by Ayutac** [comment]
> The whole point of moving to datagen is so that the changes only need to be done in one place...

Is there a wiki page or readme in the code that explains how exactly that is done? I'm new to modding and very happy I am able to understand the code so far; I feel future contributors would be confused about the data gen as well.

**Pull request merged**
