### PR TITLE
Update some textures, fix some sounds, add scrap texture

### PR DESCRIPTION
**Pull request by ProfessorProspector**

### CODE REVIEW

**Comment by modmuss50** [comment]
Ive merged some of your commits, the one with the rubber tree changes would break them.

**Comment by modmuss50** [comment]
Thanks for that! I will have to close this, but I have merged most of this PR

**Comment by ProfessorProspector** [comment]
Why would it break them? Seemed to work fine in my env

**Comment by ProfessorProspector** [comment]
Hmm it appears for some reason the java files didn't get pushed to git. I'll have to figure that out in the morning.

**Comment by modmuss50** [comment]
That would explain it

**Comment by ProfessorProspector** [comment]
Anyway the reason I changed it in the first place was because the tinker part builder was treating the top face as the side face because of the texture name. Place a rubber wood part builder down and see for yourself.

**Pull request closed without merging**
