### PR TITLE
Fixed typos in config

### PR DESCRIPTION
**Pull request by AKTheKnight**

### CODE REVIEW

**Comment by AKTheKnight** [comment]
I have no idea how I managed to change over 1500 files

**Comment by Prospector** [comment]
erm. this literally changes every single file

**Comment by Prospector** [comment]
think there's some problem

**Comment by modmuss50** [comment]
Its fucked up, not merging

**Comment by AKTheKnight** [comment]
I have no idea how. I'll just leave it, and let someone else fix it

**Comment by Prospector** [comment]
look at the file paths for those files `classes/production/TechReborn_main/`

**Comment by AKTheKnight** [comment]
huh. Seems like .gitignore didn't actually ignore anything

**Pull request closed without merging**
