### PR TITLE
Fixes Cupronickel heating coil recipe

### LINKED ISSUE #783: Rolling machine is broken
hello there,
we use MC 1.10.2 and the latest TechReborn (1.4.7.70) on our server.

the Rolling machine does... nothing... it looks like it doesnt even get power.

### PR DESCRIPTION
**Pull request by brad18**
Brings Cupronickel heating coil recipe into line with Gregtech MC 1.4.7 and fixes #783

### CODE REVIEW

**Comment by modmuss50** [comment]
Nice! Thanks

**Comment by Yulife** [comment]
Tbh we need to revise all recipes before v2 lol

**Comment by utoc** [comment]
@modmuss50 Can you maybe remerge this with the v1 tree?  Not sure how to go about it without duplicate of existing work

**Comment by modmuss50** [comment]
Ok will do, thanks for reminding me.

**Comment by modmuss50** [comment]
There: https://github.com/TechReborn/TechReborn/commits/1.10.2-v1 I plan to push a new build out soon with some of the v2 changes

**Pull request merged**
