### PR TITLE
Russian language

### PR DESCRIPTION
**Pull request by Romz24**
I noticed that the translate.techreborn.ovh website is not updating. The localization that is there is outdated and there are many missing keys for translation.

Number of keys on the site: 878
Number of keys in my transfer: 971

### CODE REVIEW

**Comment by modmuss50** [comment]
I may need to update the website with the latest source translation file.

**Comment by modmuss50** [comment]
Please check again, I should look into automating the updating of the english copy.

**Comment by Romz24** [comment]
It seems new keys have appeared, thanks for the quick response.

**Comment by Romz24** [comment]
I have added the translation on the site, thanks again.

**Comment by drcrazy** [comment]
@Romz24 Have you joined TR Discord?

**Comment by Romz24** [comment]
@drcrazy No, can you provide a link?

**Comment by drcrazy** [comment]
https://discord.gg/teamreborn

**Comment by drcrazy** [comment]
Ping me in Discord. I will add you to translators

**Pull request closed without merging**
