### PR TITLE
Remove mod menu from pom

### PR DESCRIPTION
**Pull request by natanfudge**

### CODE REVIEW

**Review by modmuss50 — CHANGES_REQUESTED** [review]
The ideal fix will be to use MM of my maven, after MMs pom has been fixed.

**Comment by natanfudge** [comment]
Either way you don't want to include optional dependencies with `modCompile` (it should be `modRuntime`), same thing with REI.

**Comment by modmuss50** [comment]
This wont work for REI as it compiles against it.

**Comment by natanfudge** [comment]
In that case you need to add `modCompileOnly` additionally. But still not `modCompile`.

**Comment by modmuss50** [comment]
That will then stop it being there when ran in dev... There are better ways to control what goes into the pom.

**Comment by natanfudge** [comment]
> That will then stop it being there when ran in dev...

No, because you will _also_ have the `modRuntime`. For optional dependencies you want to compile against, you use _both_ `modRuntime` _and_ `modCompileOnly`. What better way is there to do it?

**Comment by modmuss50** [comment]
You can use `pom.withXml` in the MavenPublication to directally control what the pom contains. In this case i think thats a better way to do it.

**Comment by natanfudge** [comment]
Can you _remove_ xml entries with that? Either way tinkering with the xml is not a better solution for [literally what compileOnly is made for](https://blog.gradle.org/introducing-compile-only-dependencies).

**Comment by modmuss50** [comment]
Having duplicate entrys isnt ideal.

**Comment by natanfudge** [comment]
In that case you can do 
```
configurations {
    optionalDependency {
        extendsFrom modRuntime
        extendsFrom modCompileOnly
    }
}

dependencies {
     optionalDependency "REI"
}

```

**Update:** It seems like this doesn't work for some reason, perhaps a Loom bug. Invoking them both individually still works. So in Kotlin DSL you can do (not really relevant in TR):
```kotlin
fun DependencyHandlerScope.optionalDependency(dep: String) {
   modRuntime(dep) {
        exclude(group = "net.fabricmc.fabric-api")
   }
   modCompileOnly(dep)
}
```

**Comment by modmuss50** [comment]
Yeah, that might be a better idea actaully.

**Comment by natanfudge** [comment]
See edit^

**Comment by modmuss50** [comment]
Closing the PR as its not the right solution. Ill look into a full fix.

**Pull request closed without merging**
