### PR TITLE
[WIP] Port/1.21.4

### PR DESCRIPTION
**Pull request by ZurrTum**

### CODE REVIEW

**Comment by Ayutac** [comment]
We don't use reflection to access private fields, that's what Access Wideners are for

**Comment by ZurrTum** [comment]
mixin ?

**Comment by Ayutac** [comment]
Nah, AccessWideners. Give me a minute.

**Comment by Ayutac** [comment]
See https://github.com/TechReborn/TechReborn/commit/af48d9462b45cdbd9b72068c03b406f570e67fad (note that the AW of TR is generated automatically from the AW of Reborn Core)

**Pull request closed without merging**
