### PR TITLE
Power system re-write, recipe fixes.

### PR DESCRIPTION
**Pull request by Dragon2488**
Please note that this version breaks all wires placed in worlds before.

### CODE REVIEW

**Comment by modmuss50** [comment]
I haven't got time to look at it now as I am leaving for the US, when I have the chance I will look over it. 👍

**Comment by modmuss50** [comment]
Looks good, just fix the merge conflicts and I will merge it.

**Comment by Dragon2488** [comment]
How should i fix it? =/

**Comment by Dragon2488** [comment]
Seems like conflicts exist because of your "energy net crash fix" commit.

**Comment by modmuss50** [comment]
I think I will be able to merge it manualy

**Comment by modmuss50** [comment]
There, Thanks 👍

**Comment by Dragon2488** [comment]
And modmuss, yes, i need push access to reppo. It will be much flexible.

**Pull request merged**
