### PR TITLE
Update to REI 3.0-pre

### PR DESCRIPTION
**Pull request by shedaniel**
This will update TechReborn to REI 3.0. Also made the label draw without a shadow (It will look better that way)

### CODE REVIEW

**Comment by modmuss50** [comment]
Is 3.0 released? 

PR looks good just want to merge this at the correct time so people arent forced onto the old version.

**Comment by shedaniel** [comment]
Yep it is, I am PRing to mods to fix this. (3.0 was out because I need to fix `java.awt`)

**Comment by shedaniel** [comment]
The old entrypoint works too. But by changing to `rei_plugins_v0`, the mod won't crash in REI 2.x.

**Comment by modmuss50** [comment]
Thanks a lot for this.

**Pull request merged**
