### PR TITLE
Fix matter fabricator uses scrapboxs when full

### PR DESCRIPTION
**Pull request by jusvit**

### CODE REVIEW

**Comment by modmuss50** [comment]
Im not sure why its including your past PR's in the changes, its not a major issue as I can just squish them but you should look into it.

**Comment by Prospector** [comment]
He needs to pull from our branch, because we merged them

**Comment by jusvit** [comment]
@ProfessorProspector How does one do that? I've been trying to get rid of my previous commits, but fell short.

**Comment by Prospector** [comment]
Hm I don't remember, its been a while since I've done stuff on a fork.

**Pull request merged**
