### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xbony2**

### CODE REVIEW

**Comment by modmuss50** [comment]
Thanks 👍

**Comment by modmuss50** [comment]
Also, @xbony2 are you the FTB wiki guy?

**Comment by xbony2** [comment]
Lead editor. Or something like that.

**Comment by modmuss50** [comment]
Ok, thanks. I'm just weighing up wiki options for techreborn at the moment. If I need more info I will contact you once I have some free time.

**Comment by xbony2** [comment]
Cool :) [Here's](https://ftb.gamepedia.com/Feed_The_Beast_Wiki:Developer-appointed_curator_program) a useful page for you.

**Comment by xbony2** [comment]
I'm probably going to write some documentation on it myself, once 1.9 is semi-stable and Unity textures are in place (I'd hate to create a tilesheet [an image with all of the mod's icons] and have to redo it a few days later).

**Pull request merged**
