### PR TITLE
Various fixes to cells for 1.7.10

### PR DESCRIPTION
**Pull request by wormzjl**
Tested to be working

### CODE REVIEW

**Comment by modmuss50** [comment]
1.7.10 ?!

**Comment by modmuss50** [comment]
I guess I can do one last build, if the jenkins still works...

**Comment by wormzjl** [comment]
Cuz I'm staying with Reika :3

**Comment by modmuss50** [comment]
Are there any other changes for 1.7 that I could add?

**Comment by wormzjl** [comment]
I'd suggest removing the ic2 api from the jar, as it could cause some issues

**Comment by modmuss50** [comment]
Ok I will look into it, it would be nice to leave it in a state where it doesn't break in the future.

**Comment by wormzjl** [comment]
There are also a bunch of recipes I want to fix with regard to gt2, but this could take some time

**Comment by modmuss50** [comment]
Ok, I cannot easily remove the IC2 api from the jar as some of the interfaces are required..

**Comment by modmuss50** [comment]
Ok, I updated all deps and pushed to curse. Also includes your PR from august.

**Comment by wormzjl** [comment]
thx

**Pull request merged**
