### PR TITLE
Mining Rig

### PR DESCRIPTION
**Pull request by jusvit**
This pull request adds the Mining Rig, a multi-block automated mining machine (Quarry).

Basically works as a quarry but with modifiable drill heads which alter the functionality of the rig (Radius, speed, modifiers).

Instead of a huge world hole, the mining rig doesn't dig directly underneath, instead clearing a few blocks down before starting (Preserve the nature).

[Do not merge, I will when appropriately finished]

### CODE REVIEW

**Comment by Romz24** [comment]
It sounds very interesting, I'm looking forward to the release to test it.

**Comment by Sturmlilie** [comment]
Is this meant to be reviewed? What is the purpose of this PR? If you don't want feedback, you can mark them as "draft".

**Comment by jusvit** [comment]
> Is this meant to be reviewed? What is the purpose of this PR? If you don't want feedback, you can mark them as "draft".

In due course, this just to keep track of merge compatibility and the checks. In addition to provide as a hub of discussion/changes. This will be more active in about a week.

**Comment by Romz24** [comment]
Hello, how is your development progress?

**Comment by jusvit** [comment]
Abandoned

**Pull request closed without merging**
