### PR TITLE
Added grinder recipes for gems -> dust

### PR DESCRIPTION
**Pull request by brnbrd**

### CODE REVIEW

**Comment by modmuss50** [comment]
Nice, thanks again 👍

**Comment by brnbrd** [comment]
modmuss50, do you know where I could get a link to GregTech 2.78 for testing?

**Comment by Prospector** [comment]
are you on our IRC channel? come on and I'll give you a download #TechReborn on esper

**Comment by brnbrd** [comment]
Just joined

**Comment by Yulife** [comment]
We probably need to do one big commit where we mirror all recipes from the old days, right now most machines recipes are not done

**Comment by modmuss50** [comment]
They do not need to be exact, as long as everything fits in we should be good.

**Pull request merged**
