### PR TITLE
Prevent IllegalStateException

### PR DESCRIPTION
**Pull request by aria1th**
for some reason server packet can get corrupted, but its connection should not fail.

### CODE REVIEW

**Comment by modmuss50** [comment]
Can you provide a log where this happens, if the packet is corrupted it should 100% crash the game as not doing so will leave the client in an inconsitent state.

**Comment by aria1th** [comment]
`[22:24:21] [Render thread/INFO]: [WTHIT] Received config from the server: {"minecraft:item_entity":true,"minecraft:pet.owner":true,"minecraft:override.powder_snow":false,"minecraft:override.infested":false,"minecraft:override.trapped_chest":false}
[22:24:21] [Netty Client IO #11/ERROR]: Failed to ser/de techreborn:scrapbox/auto/oak_fence_gate
reborncore.common.crafting.serde.RecipeSerdeException: Failed to ser/de techreborn:scrapbox/auto/oak_fence_gate
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at reborncore.common.crafting.RebornRecipeType.read(RebornRecipeType.java:54) ~[reborncore-5.1.0-3ce5e61612df6b0e.jar:?]
	at reborncore.common.crafting.RebornRecipeType.read(RebornRecipeType.java:74) ~[reborncore-5.1.0-3ce5e61612df6b0e.jar:?]
	at reborncore.common.crafting.RebornRecipeType.read(RebornRecipeType.java:40) ~[reborncore-5.1.0-3ce5e61612df6b0e.jar:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.readRecipe(SynchronizeRecipesS2CPacket:45) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readCollection(PacketByteBuf:123) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readList(PacketByteBuf:136) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.<init>(SynchronizeRecipesS2CPacket:22) ~[?:?]
	at net.minecraft.network.NetworkState$PacketHandler.createPacket(NetworkState:417) ~[?:?]
	at net.minecraft.network.NetworkState.getPacketHandler(NetworkState:469) ~[?:?]
	at net.minecraft.network.DecoderHandler.decode(DecoderHandler:36) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: minecraft:air did not exist
	at reborncore.common.crafting.RecipeUtils.deserializeItem(RecipeUtils.java:71) ~[reborncore-5.1.0-3ce5e61612df6b0e.jar:?]
	at reborncore.common.crafting.RecipeUtils.lambda$deserializeItems$0(RecipeUtils.java:61) ~[reborncore-5.1.0-3ce5e61612df6b0e.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at reborncore.common.crafting.RecipeUtils.deserializeItems(RecipeUtils.java:61) ~[reborncore-5.1.0-3ce5e61612df6b0e.jar:?]
	at reborncore.common.crafting.serde.AbstractRecipeSerde.getOutputs(AbstractRecipeSerde.java:61) ~[reborncore-5.1.0-3ce5e61612df6b0e.jar:?]
	at reborncore.common.crafting.serde.RebornRecipeSerde.fromJson(RebornRecipeSerde.java:46) ~[reborncore-5.1.0-3ce5e61612df6b0e.jar:?]
	at reborncore.common.crafting.RebornRecipeType.read(RebornRecipeType.java:52) ~[reborncore-5.1.0-3ce5e61612df6b0e.jar:?]
	... 47 more
[22:24:21] [Render thread/INFO]: [STDOUT]: Minimap session finalized.
[22:24:21] [Render thread/INFO]: [STDOUT]: Finalizing world map session... `

**Comment by aria1th** [comment]
sometimes it provides log, sometimes it does not even provide log and crash silently, I'd say silent crash is something that really matters

**Comment by aria1th** [comment]
additionally I got this by printing JSONObject
			RebornCore.LOGGER.warn(jsonObject.toString());
`[23:05:39] [Netty Client IO #5/WARN]: {"item":"minecraft:air"}
[23:05:39] [Netty Client IO #5/WARN]: minecraft:air did not exist
[23:05:39] [Netty Client IO #5/WARN]: {"item":"minecraft:air"}
[23:05:39] [Netty Client IO #5/WARN]: minecraft:air did not exist`

**Comment by Ayutac** [comment]
This seems like an error that shouldn't happen. Before silencing it, can someone else reproduce?

What is your MC and TR version? Other mods?

**Comment by aria1th** [comment]
Its 1.18.1, TR version is latest (5.1.0). Fabric loader 0.13.2, Fabric API 0.46.4.
Additional Informations : 
At first server boot, there's no problem with recipes and oak fence gate recipe appears normally in REI.
After 8+ hours of server running, it silently removes oak fence gate recipe from scrapbox (server side) and sends it to client. Client fails to verify if its valid recipe. It does not generate crash report and silently fails to connect to server especially when **Sodium + Indium + Continuity + IRIS** is in client. If those mods are not present, it throws RecipeSerde Exception normally as it should. Well, sometimes it does not. Its behavior is exactly same as when you receive too big size packets.

I have far more mods running
[mods.txt](https://github.com/TechReborn/TechReborn/files/8165783/mods.txt)
 in server, but nothing appeared in server side log.

**Comment by drcrazy** [comment]
@aria1th  Could this one just be closed due to Dispenser recipe fix?

**Comment by aria1th** [comment]
Yes I believe all the problems were from that

**Pull request closed without merging**
