### PR TITLE
Amethyst Additions

### PR DESCRIPTION
**Pull request by xanthian**
implements grinding of amethyst blocks to dust
1 Block = 2 Dust
implements production of amethyst shards from dust + tnt in implosion compressor
8 Dust + 16 TNT = 16 Shards + 1 Quartz Dust

Conversion ratio = 1 Stack of Amethyst Block + 1 Stack of TNT = 1 Stack of Shard + 4 Quartz Dust

Quartz dust is because irl science..
I feel its not OP and its probably a little on the stingy side, but for the ease and automation it provides I feel it needs to be.

### CODE REVIEW

**Comment by triangular2357** [comment]
I think 8 dust + tnt/ender eyes => 8 shards + ash/ender eye small dust would fit more into the implosion compressor (would be more like other implosion compressor recipes)

**Comment by xanthian** [comment]
> I think 8 dust + TNT/ender eyes => 8 shards + ash/ender eye small dust would fit more into the implosion compressor (would be more like other implosion compressor recipes)

8 shards is just too stingy IMO.
2 stacks of TNT and amethyst block for 1 stack of shards?

none of the implosion compressor recipes use ender eyes as in input?
i replicated the end crystal ones.
there's very little use for small ender eye dust/ender dust, so wanted some variation on returns.
as I said, quartz is cos 'science'

**Comment by Ayutac** [comment]
Lol @drcrazy this one I had zero hands in. All thanks to Xanthian

**Comment by triangular2357** [comment]
> none of the implosion compressor recipes use ender eyes as in input?
> i replicated the end crystal ones.

oops I meant end crystals

>  there's very little use for small ender eye dust/ender dust

yeah true

**Pull request merged**
